'use client';
import { useEffect, useState } from 'react';
import AppShell from '@/components/AppShell';
import { listStudents, listGroups, getPaymentsForStudent, togglePayment, MONTHS } from '@/lib/dataStore';

export default function PaymentsPage() {
  const [students, setStudents] = useState([]);
    const [groups, setGroups] = useState([]);
      const [groupId, setGroupId] = useState('');
        const [month, setMonth] = useState(MONTHS[0].key);
          const [paymentsMap, setPaymentsMap] = useState({});
            const [loading, setLoading] = useState(true);

              useEffect(() => {
                  (async () => {
                        const [studentList, groupList] = await Promise.all([listStudents(), listGroups()]);
                              setStudents(studentList);
                                    setGroups(groupList);
                                          if (groupList.length) setGroupId(groupList[0].id);
                                                setLoading(false);
                                                    })();
                                                      }, []);

                                                        const filteredStudents = students.filter((s) => s.group_id === groupId);

                                                          useEffect(() => {
                                                              (async () => {
                                                                    const map = {};
                                                                          for (const s of filteredStudents) {
                                                                                  map[s.id] = await getPaymentsForStudent(s.id);
                                                                                        }
                                                                                              setPaymentsMap(map);
                                                                                                  })();
                                                                                                    }, [groupId, students]);

                                                                                                      const handleToggle = async (studentObj) => {
                                                                                                          const list = paymentsMap[studentObj.id] || [];
                                                                                                              const existing = list.find((p) => p.month === month);
                                                                                                                  const updated = await togglePayment(studentObj.id, month, existing?.paid || false, studentObj.monthly_price);
                                                                                                                      setPaymentsMap((prev) => {
                                                                                                                            const filtered = (prev[studentObj.id] || []).filter((p) => p.month !== month);
                                                                                                                                  return { ...prev, [studentObj.id]: [...filtered, updated] };
                                                                                                                                      });
                                                                                                                                        };

                                                                                                                                          const isPaid = (studentId) =>
                                                                                                                                              (paymentsMap[studentId] || []).find((p) => p.month === month)?.paid || false;

                                                                                                                                                return (
                                                                                                                                                    <AppShell>
                                                                                                                                                          <header className="mb-6">
                                                                                                                                                                  <h1 className="font-display text-2xl font-extrabold text-slate-100">المصروفات الشهرية</h1>
                                                                                                                                                                          <p className="text-slate-400 text-sm mt-1">اختر المجموعة والشهر، ثم اضغط على أي اسم لتغيير حالة الدفع — يُحفظ تلقائيًا</p>
                                                                                                                                                                                </header>

                                                                                                                                                                                      <div className="glass-card p-4 mb-4 flex flex-wrap gap-3">
                                                                                                                                                                                              <select value={groupId} onChange={(e) => setGroupId(e.target.value)} className="input-field w-auto min-w-[220px]">
                                                                                                                                                                                                        {loading && <option>جارٍ التحميل...</option>}
                                                                                                                                                                                                                  {groups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}
                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                  <select value={month} onChange={(e) => setMonth(e.target.value)} className="input-field w-auto">
                                                                                                                                                                                                                                            {MONTHS.map((m) => <option key={m.key} value={m.key}>{m.label}</option>)}
                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                            <span className="mr-auto flex items-center text-sm text-slate-400">{filteredStudents.length} طالب في المجموعة</span>
                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                        <div className="glass-card p-6">
                                                                                                                                                                                                                                                                                {filteredStudents.length === 0 && !loading && (
                                                                                                                                                                                                                                                                                          <p className="text-slate-400 text-center py-8">لا يوجد طلاب في هذه المجموعة</p>
                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
                                                                                                                                                                                                                                                                                                                    {filteredStudents.map((s) => {
                                                                                                                                                                                                                                                                                                                                const paid = isPaid(s.id);
                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                          <button key={s.id} onClick={() => handleToggle(s)}
                                                                                                                                                                                                                                                                                                                                                                          className={`rounded-2xl p-5 text-center border transition-all
                                                                                                                                                                                                                                                                                                                                                                                            ${paid ? 'bg-teal-500/15 border-teal-400/40' : 'bg-white/[0.03] border-white/[0.08] hover:border-white/[0.2]'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                            <p className="font-bold text-slate-100 mb-2">{s.full_name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                            <span className={`inline-block px-3 py-1 rounded-full text-xs font-bold ${paid ? 'bg-teal-500/20 text-teal-300' : 'bg-red-500/15 text-red-400'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                              {paid ? 'مدفوع' : 'غير مدفوع'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </AppShell>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }