'use client';
import { useEffect, useState } from 'react';
import AppShell from '@/components/AppShell';
import { Check } from 'lucide-react';
import { listStudents, listGroups, getAttendanceForStudent, toggleAttendance, MONTHS } from '@/lib/dataStore';

export default function AttendancePage() {
  const [students, setStudents] = useState([]);
    const [groups, setGroups] = useState([]);
      const [groupId, setGroupId] = useState('');
        const [month, setMonth] = useState(MONTHS[0].key);
          const [attendanceMap, setAttendanceMap] = useState({});
            const [loading, setLoading] = useState(true);

              useEffect(() => {
                  (async () => {
                        const [studentList, groupList] = await Promise.all([listStudents(), listGroups()]);
                              setStudents(studentList);
                                    setGroups(groupList);
                                          if (groupList.length) setGroupId(groupList[0].id);
                                                setLoading(false);
                                                    })();
                                                      }, []);

                                                        const filteredStudents = students.filter((s) => s.group_id === groupId);

                                                          useEffect(() => {
                                                              (async () => {
                                                                    const map = {};
                                                                          for (const s of filteredStudents) {
                                                                                  map[s.id] = await getAttendanceForStudent(s.id);
                                                                                        }
                                                                                              setAttendanceMap(map);
                                                                                                  })();
                                                                                                    }, [groupId, students]);

                                                                                                      const handleToggle = async (studentId, lessonNumber) => {
                                                                                                          const existing = (attendanceMap[studentId] || []).find(
                                                                                                                (a) => a.month === month && a.lesson_number === lessonNumber
                                                                                                                    );
                                                                                                                        const updated = await toggleAttendance(studentId, month, lessonNumber, existing?.present || false);
                                                                                                                            setAttendanceMap((prev) => {
                                                                                                                                  const list = prev[studentId] || [];
                                                                                                                                        const filtered = list.filter((a) => !(a.month === month && a.lesson_number === lessonNumber));
                                                                                                                                              return { ...prev, [studentId]: [...filtered, updated] };
                                                                                                                                                  });
                                                                                                                                                    };

                                                                                                                                                      const isPresent = (studentId, lessonNumber) =>
                                                                                                                                                          (attendanceMap[studentId] || []).find((a) => a.month === month && a.lesson_number === lessonNumber)?.present || false;

                                                                                                                                                            return (
                                                                                                                                                                <AppShell>
                                                                                                                                                                      <header className="mb-6">
                                                                                                                                                                              <h1 className="font-display text-2xl font-extrabold text-slate-100">الحضور</h1>
                                                                                                                                                                                      <p className="text-slate-400 text-sm mt-1">اختر المجموعة والشهر، ثم اضغط على أي حصة لتغيير حالتها — يُحفظ تلقائيًا</p>
                                                                                                                                                                                            </header>

                                                                                                                                                                                                  <div className="glass-card p-4 mb-4 flex flex-wrap gap-3">
                                                                                                                                                                                                          <select value={groupId} onChange={(e) => setGroupId(e.target.value)} className="input-field w-auto min-w-[220px]">
                                                                                                                                                                                                                    {loading && <option>جارٍ التحميل...</option>}
                                                                                                                                                                                                                              {groups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}
                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                              <select value={month} onChange={(e) => setMonth(e.target.value)} className="input-field w-auto">
                                                                                                                                                                                                                                                        {MONTHS.map((m) => <option key={m.key} value={m.key}>{m.label}</option>)}
                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                        <span className="mr-auto flex items-center text-sm text-slate-400">{filteredStudents.length} طالب في المجموعة</span>
                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                    <div className="glass-card p-4">
                                                                                                                                                                                                                                                                                            {filteredStudents.length === 0 && !loading && (
                                                                                                                                                                                                                                                                                                      <p className="text-slate-400 text-center py-8">لا يوجد طلاب في هذه المجموعة</p>
                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                      <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                {filteredStudents.map((s) => (
                                                                                                                                                                                                                                                                                                                                            <div key={s.id} className="border-b border-slate-700/50 pb-4 last:border-0">
                                                                                                                                                                                                                                                                                                                                                          <p className="text-slate-200 font-bold mb-2">{s.full_name}</p>
                                                                                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-6 sm:grid-cols-12 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                        {Array.from({ length: 12 }, (_, i) => i + 1).map((n) => (
                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                              key={n}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => handleToggle(s.id, n)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={`lesson-cell ${isPresent(s.id, n) ? 'lesson-present' : 'lesson-absent'}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isPresent(s.id, n) ? <Check size={16} /> : n}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </AppShell>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }